# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_rasenna_rcpp_hello`)
}

#' Resample telemetry fixes to a standard temporal resolution.
#' @param x Matrix with telemetry locations.
#' @param t Datetime of the location in Unix time (numeric).
#' @param freq Frequency of resampling.
#' @param freq_low Lower threshold (proportion) of frequency to keep.
#' @param freq_high Higher threshold (proportion) of frequency to assign to
#'   the same track.
.resample <- function(t, freq, th_low = 0.9, th_high = 1.1) {
    .Call(`_rasenna_resample`, t, freq, th_low, th_high)
}

