# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bearing of telemetry fixes.
#' @param x horizontal (longitude) coordinate vector.
#' @param y vertical (latitude) coordinate vector.
.bearing <- function(x, y) {
    .Call(`_rasenna_bearing`, x, y)
}

#' Truning angle between telemetry fixes.
#' @param x horizontal (longitude) coordinate vector.
#' @param y vertical (latitude) coordinate vector.
.turning_angle <- function(x, y) {
    .Call(`_rasenna_turning_angle`, x, y)
}

#' Distance between telemetry fixes.
#' @param x horizontal (longitude) coordinate vector.
#' @param y vertical (latitude) coordinate vector.
.distance <- function(x, y) {
    .Call(`_rasenna_distance`, x, y)
}

#' Resample telemetry fixes to a standard temporal resolution.
#' @param t Datetime of the location in Unix time (numeric).
#' @param freq Frequency of resampling.
#' @param th_low Lower threshold (proportion) of frequency to keep.
#' @param th_high Higher threshold (proportion) of frequency to assign to
#'   the same track.
.resample <- function(t, freq, th_low = 0.9, th_high = 1.1) {
    .Call(`_rasenna_resample`, t, freq, th_low, th_high)
}

